name: Deploy WebLaunch

on:
  push:
    branches:
      - main

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      - name: Validar HTML con HTMLHint
        uses: wearerequired/htmlhint-action@v1
        with:
          files: "*.html"


      - name: Validar CSS
        run: npx stylelint "**/*.css"  

      - name: Ejecutar pruebas con Jest
        run: npm test
      